plugins {
    id 'java'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    mavenCentral()
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
    maven { url = 'https://repo.codemc.io/repository/maven-public/' }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.21.4-R0.1-SNAPSHOT'
    compileOnly 'fr.xephi.authme:AuthMe:5.6.0'
    implementation 'com.google.code.gson:gson:2.11.0'
}

processResources {
    inputs.property 'version', project.version

    filesMatching('plugin.yml') {
        expand 'version': project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = project.java_version as int
}

java {
    withSourcesJar()
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}
